server:
  port: 8080
  shutdown: graceful # tell the server to wait for executing requests to finish before shutdown

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true # on K8s this is turned on by default
      group:
        readiness:
          include: "readinessState,example"
  endpoints:
    web:
      exposure:
        include: "*"

