apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-probes
  name: k8s-probes
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-probes
  type: NodePort
